---

- name: Install Dovecot packages
  apt:
    pkg: '{{ item }}'
    state: 'present'
    install_recommends: 'no'
  with_flattened:
    - [ 'dovecot-core' ]
    - [ '{{ "dovecot-imapd" if ("imap" in dovecot_protocols or "imaps" in dovecot_protocols) else [] }}' ]
    - [ '{{ "dovecot-pop3d" if ("pop3" in dovecot_protocols or "pop3s" in dovecot_protocols) else [] }}' ]
    - [ '{{ "dovecot-managesieved" if "managesieve" in dovecot_protocols else [] }}' ]

- name: Install Dovecot GSSAPI package
  apt:
    pkg: 'dovecot-gssapi'
    state: 'present'
    install_recommends: 'no'
  when: ('gssapi' in dovecot_auth_mechanisms)

- name: Generate Dovecot configuration
  template:
    src: "{{ lookup('template_src', 'etc/dovecot/local.conf.j2') }}"
    dest: '/etc/dovecot/local.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Restart dovecot' ]

- name: Configure firewall for Dovecot
  template:
    src: 'etc/ferm/filter-input.d/dovecot.conf.j2'
    dest: '/etc/ferm/filter-input.d/dovecot.conf'
    owner: 'root'
    group: 'adm'
    mode: '0644'
  notify: [ 'Restart ferm' ]
