---

- name: Install Dovecot packages
  apt:
    pkg: '{{ item }}'
    state: 'present'
    install_recommends: 'no'
  with_flattened:
    - [ 'dovecot-core' ]
    - [ '{{ "dovecot-imapd" if ("imap" in dovecot_protocols or "imaps" in dovecot_protocols) else [] }}' ]
    - [ '{{ "dovecot-pop3d" if ("pop3" in dovecot_protocols or "pop3s" in dovecot_protocols) else [] }}' ]
    - [ '{{ "dovecot-managesieved" if "managesieve" in dovecot_protocols else [] }}' ]
    - [ '{{ "dovecot-gssapi" if "gssapi" in dovecot_auth_mechanisms else [] }}' ]

- name: Disable default configuration
  lineinfile:
    dest: '/etc/dovecot/conf.d/{{ item.path }}'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    backrefs: 'yes'
  with_items:
    - { path: '10-auth.conf', regexp: '^(!include auth-system\.conf\.ext)', line: '#\1' }
    - { path: '10-mail.conf', regexp: '^(mail_location.*)', line: '#\1' }

- name: Generate Dovecot configuration
  template:
    src: "{{ lookup('template_src', 'etc/dovecot/local.conf/ansible.j2') }}"
    dest: '/etc/dovecot/local.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Restart dovecot' ]

- name: Generate Dovecot deny user list
  template:
    src: "{{ lookup('template_src', 'etc/dovecot/dovecot.deny.j2') }}"
    dest: '/etc/dovecot/dovecot.deny'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Configure firewall for Dovecot
  template:
    src: 'etc/ferm/filter-input.d/dovecot.conf.j2'
    dest: '/etc/ferm/filter-input.d/dovecot.conf'
    owner: 'root'
    group: 'adm'
    mode: '0644'
  notify: [ 'Restart ferm' ]

- name: Check krb5 keytab permissions
  file:
    path: '{{ dovecot_krb5_keytab }}'
    owner: 'root'
    group: 'dovecot'
    mode: '0640'
